version: '3.2'
# run Cypress tests and exit with command
#   docker-compose up --exit-code-from cypress
services:
  react:
    build:
        context: ./react
        dockerfile: ./Dockerfile
    ports:
      - "80:80"
  cypress:
    image: "cypress/included:12.0.0"
    depends_on:
      - react
    environment:
      - CYPRESS_baseUrl=http://react:80
    working_dir: /e2e
    volumes:
      - ./:/e2e